repos:
  # Websec hook is MANDATORY, DO NOT comment it.
  - repo: https://github.com/melisource/fury_websec-git-hooks
    rev: v1.1.0
    hooks:
      - id: pre_commit_hook
        stages: [commit]
      - id: post_commit_hook
        stages: [post-commit]

  # Datasec hook is MANDATORY, DO NOT comment it.
  - repo: https://github.com/melisource/fury_datasec-git-hooks
    rev: 1.0.3
    hooks:
      - id: pre_commit_hook
        stages: [commit]
        verbose: true