package com.mercadopago.client.order;

import lombok.Builder;
import lombok.Getter;

// API version: 1ff4822a-2dfd-4393-800e-a562edb3fe32

/**
 * Request object representing the payment method to be used in an order payment. Includes the
 * method identifier, type, tokenized card data, installment configuration, and statement
 * descriptor for the cardholder's bill.
 */
@Getter
@Builder
public class OrderPaymentMethodRequest {

    /** Identifier of the payment method (e.g. "visa", "master", "pix"). */
    private String id;

    /** Type of the payment method (e.g. "credit_card", "debit_card", "bank_transfer"). */
    private String type;

    /** Card token generated by MercadoPago.js for secure card data handling. */
    private String token;

    /** Number of installments selected for the payment. */
    private int installments;

    /** Text that will appear on the cardholder's billing statement (e.g. "MERCADOPAGO"). */
    private String statementDescriptor;
}
