package com.mercadopago.resources.order;

import lombok.Getter;

// API version: 1ff4822a-2dfd-4393-800e-a562edb3fe32

/**
 * Resource representing the payment method used in an order payment.
 * Includes details such as the method type, card or token references, installment
 * configuration, barcode/QR data for offline methods, and 3DS transaction security.
 */
@Getter
public class OrderPaymentMethod {
    /** Identifier of the payment method (e.g., "visa", "pix", "bolbradesco"). */
    private String id;

    /** Identifier of the saved card used for this payment. */
    private String cardId;

    /** Type of payment method (e.g., "credit_card", "debit_card", "ticket", "bank_transfer"). */
    private String type;

    /** Tokenized card data generated by the MercadoPago SDK for secure card transactions. */
    private String token;

    /** Number of installments selected for this payment. */
    private Integer installments;

    /** Text that appears on the payer's card statement (e.g., "MERCADOPAGO"). */
    private String statementDescriptor;

    /** Barcode content for offline payment methods such as boleto. */
    private String barcodeContent;

    /** Reference code for identifying the payment at the financial institution. */
    private String reference;

    /** Verification code associated with the payment method. */
    private String verificationCode;

    /** Financial institution responsible for processing the payment. */
    private String financialInstitution;

    /** QR code string for QR-based payment methods such as Pix. */
    private String qrCode;

    /** Base64-encoded QR code image for rendering in the client application. */
    private String qrCodeBase64;

    /** Digitable line for boleto or similar offline payment methods. */
    private String digitableLine;

    /** URL where the payer can view or download the payment ticket or voucher. */
    private String ticketUrl;

    /** Transaction security configuration for 3DS authentication flows. */
    private OrderTransactionSecurity transactionSecurity;

    /** End-to-end identifier for tracking the payment across systems (e.g., Pix e2eId). */
    private String e2eId;

    /** URL to redirect the payer for completing the payment in an external flow. */
    private String redirectUrl;
}
