package com.mercadopago.client.payment;

import lombok.Builder;
import lombok.Getter;

/**
 * Request object containing 3-D Secure (3DS) authentication data for a payment.
 * Used when the merchant performs external 3DS authentication and needs to
 * forward the authentication results to MercadoPago.
 */
@Getter
@Builder
public class PaymentAuthenticationRequest {
    /** Authentication type (e.g. "external_threeds"). */
    private final String type;

    /** Authentication cryptogram generated by the 3DS process. */
    private final String cryptogram;

    /** 3DS Server transaction identifier. */
    private final String threeDsServerTransId;

    /** Electronic Commerce Indicator returned by the 3DS authentication. */
    private final String eci;

    /** Directory Server transaction identifier. */
    private final String dsTransId;

    /** Access Control Server transaction identifier. */
    private final String acsTransId;

    /** Version of the 3-D Secure protocol used (e.g. "2.1.0", "2.2.0"). */
    private final String threeDsVersion;

    /** Authentication status result (e.g. "Y" for authenticated, "N" for not authenticated). */
    private final String authenticationStatus;
}
