package com.mercadopago.client.payment;

import java.math.BigDecimal;
import java.time.OffsetDateTime;
import java.util.List;
import java.util.Map;
import lombok.Builder;
import lombok.Getter;

/**
 * Request object used to create a new payment through the MercadoPago Payments API.
 * Contains all the parameters needed to describe a payment, including the transaction
 * amount, payment method, payer details, and additional fraud-prevention information.
 *
 * @see <a href="https://www.mercadopago.com/developers/en/reference/payments/_payments/post">Payments API reference</a>
 */
@Getter
@Builder
public class PaymentCreateRequest {
  /** Additional data that improves fraud analysis and conversion rates. */
  private final PaymentAdditionalInfoRequest additionalInfo;

  /** Fee collected by a marketplace or MercadoPago application. */
  private final BigDecimal applicationFee;

  /** When {@code true}, the payment can only be approved or rejected; otherwise an in-process status is possible. */
  private final Boolean binaryMode;

  /** URL where MercadoPago performs the final redirect (used for bank transfers). */
  private final String callbackUrl;

  /** Discount campaign identifier. */
  private final Long campaignId;

  /** Whether the payment should be captured immediately ({@code true}) or only reserved ({@code false}). */
  private final Boolean capture;

  /** Amount of the coupon discount applied to the payment. */
  private final BigDecimal couponAmount;

  /** Discount campaign code. */
  private final String couponCode;

  /** Payment expiration date and time. */
  private final OffsetDateTime dateOfExpiration;

  /** Payment reason or item title shown to the payer. */
  private final String description;

  /** Identifier of the differential pricing scheme for financing-fee absorption. */
  private final Long differentialPricingId;

  /** External reference identifier provided by the merchant in their own system. */
  private final String externalReference;

  /** Number of installments selected by the payer. */
  private final Integer installments;

  /** Identifier of the payment method issuer (e.g. bank or card issuer). */
  private final String issuerId;

  /** Merchant account identifier used in complex payment scenarios. */
  private final String merchantAccountId;

  /** Configuration for merchant anti-fraud services. */
  private final PaymentMerchantServicesRequest merchantServices;

  /** Custom key-value metadata attached to the payment by the merchant. */
  private final Map<String, Object> metadata;

  /** Net amount received by the seller after fees. */
  private final BigDecimal netAmount;

  /** Webhook URL where MercadoPago sends notifications about payment status changes. */
  private final String notificationUrl;

  /** Associated purchase order information. */
  private final PaymentOrderRequest order;

  /** Payer information (email, identification, address, etc.). */
  private final PaymentPayerRequest payer;

  /** Forward data for Payment Facilitator or recurring-payment integrations. */
  private final PaymentForwardDataRequest forwardData;

  /** Identifier of the payment method chosen by the payer (e.g. "visa", "pix"). */
  private final String paymentMethodId;

  /** Payment method option identifier for specific payment flows. */
  private final String paymentMethodOptionId;

  /** Processing mode that determines whether a specific merchant account is used. */
  private final String processingMode;

  /** Tokenized card identifier generated by MercadoPago's card-tokenization flow. */
  private final String token;

  /** Total transaction amount to be charged. */
  private final BigDecimal transactionAmount;

  /** Additional transaction details such as the financial institution. */
  private final PaymentTransactionDetailsRequest transactionDetails;

  /** Point-of-interaction data describing the context of the payment origin. */
  private final PaymentPointOfInteractionRequest pointOfInteraction;

  /** Sponsor (platform) identifier for marketplace payments. */
  private final Long sponsorId;

  /** Description that appears on the payer's card or bank statement (e.g. "MERCADOPAGO"). */
  private final String statementDescriptor;

  /** List of taxes applied to this payment. */
  private final List<PaymentTaxRequest> taxes;

  /** Payment method details including type, rules, and authentication. */
  private final PaymentMethodRequest paymentMethod;

  /** 3-D Secure mode for the payment (e.g. "optional", "mandatory", "not_supported"). */
  private final String threeDSecureMode;

  /** Payer and collector amount details for cross-currency payments. */
  private final PaymentAmountsRequest amounts;

  /** Counter-currency information for cross-border payments. */
  private final PaymentCounterCurrencyRequest counterCurrency;
}
