package com.mercadopago.resources;

import com.mercadopago.net.MPResource;
import com.mercadopago.resources.customer.CustomerCardCardholder;
import java.time.OffsetDateTime;
import lombok.EqualsAndHashCode;
import lombok.Getter;

/**
 * Represents a tokenized card used to process secure payment transactions in the MercadoPago API.
 *
 * <p>Card tokens are generated by sending card data to the MercadoPago server, which returns a
 * token that can be used to complete payment transactions without exposing sensitive card details.
 * This resource is intended for testing purposes in sandbox environments.
 *
 * @see <a href="https://www.mercadopago.com.br/developers/en/reference/card_token/_card_token/post">
 *     Card Token API Reference</a>
 */
@Getter
@EqualsAndHashCode(callSuper = true)
public class CardToken extends MPResource {

  /** Unique identifier of the card token. */
  private String id;

  /** Identifier of the associated card. */
  private String cardId;

  /** First six digits of the card number (BIN). */
  private String firstSixDigits;

  /** Expiration month of the card (1-12). */
  private Integer expirationMonth;

  /** Expiration year of the card (four-digit format). */
  private Integer expirationYear;

  /** Last four digits of the card number. */
  private String lastFourDigits;

  /** Information about the cardholder (name and identification). */
  private CustomerCardCardholder cardholder;

  /** Current status of the card token (e.g., active). */
  private String status;

  /** Date and time when the card token was created. */
  private OffsetDateTime dateCreated;

  /** Date and time when the card token was last updated. */
  private OffsetDateTime dateLastUpdated;

  /** Date and time when the card token expires. */
  private OffsetDateTime dateDue;

  /** Whether the Luhn algorithm validation is applied to the card number. */
  private Boolean luhnValidation;

  /** Whether the token was created in production (live) mode. */
  private Boolean liveMode;

  /** Whether the token requires ESC (Electronic Security Code). */
  private Boolean requireEsc;

  /** Total length of the card number. */
  private Integer cardNumberLength;

  /** Length of the card's security code (CVV). */
  private Integer securityCodeLength;
}
