package com.mercadopago.client.customer;

import com.mercadopago.resources.customer.CustomerCardIssuer;
import lombok.Builder;
import lombok.Getter;

/**
 * Request DTO used to associate a new card with a customer. The card token is generated on the
 * frontend using the MercadoPago.js SDK, ensuring that sensitive card data never reaches your
 * server directly. Once associated, the card can be reused in future payments.
 *
 * @see <a href="https://www.mercadopago.com.br/developers/en/reference/cards">Cards API Reference</a>
 */
@Getter
@Builder
public class CustomerCardCreateRequest {
  /** Temporary card token generated by MercadoPago.js on the frontend. */
  private final String token;

  /** Card issuer information (e.g., issuing bank details). */
  private final CustomerCardIssuer issuer;

  /** Payment method identifier for the card (e.g., "visa", "master", "amex"). */
  private final String paymentMethodId;
}
