name: CI

on:
  push:
    branches: ["master", "develop"]
  pull_request:
    branches: ["master", "develop"]

jobs:
  test:
    name: Test on Java ${{ matrix.java-version }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        java-version: ["11", "17", "21"]

    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v4

      - name: Setup Java ${{ matrix.java-version }}
        uses: actions/setup-java@b6effb05e454b25005698d916606bdc6ffcbf961 # v4
        with:
          java-version: ${{ matrix.java-version }}
          distribution: "temurin"

      - name: Compile
        run: mvn compile --no-transfer-progress

      - name: Run unit tests
        run: mvn test --no-transfer-progress -Dtest="**/*Test" -DfailIfNoTests=false

      - name: Dependency review
        if: github.event_name == 'pull_request'
        uses: actions/dependency-review-action@a1d282b36b6f3519aa1f3fc636f609c47dddb294 # v4
        with:
          fail-on-severity: high
